import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'app_theme.dart';
import 'trip_detail_screen.dart';
import 'admin_trip_detail_view.dart';
import 'user_manager.dart';

class Trip {
  final String id;
  final String driverName;
  final String consignee;
  final String containerNumber;
  final String vehicleNumber;
  String? destination;
  double? startingKm;
  String? startingImageUrl;
  double? endingKm;
  String? endingImageUrl;
  bool isCompleted;

  Trip({
    required this.id,
    required this.driverName,
    required this.consignee,
    required this.containerNumber,
    required this.vehicleNumber,
    this.destination,
    this.startingKm,
    this.startingImageUrl,
    this.endingKm,
    this.endingImageUrl,
    this.isCompleted = false,
  });

  factory Trip.fromMap(Map<String, dynamic> map) {
    return Trip(
      id: map['id'],
      driverName: map['driver_name'],
      consignee: map['consignee'] ?? '',
      containerNumber: map['container_number'] ?? '',
      vehicleNumber: map['vehicle_number'] ?? '',
      destination: map['destination'],
      startingKm: map['starting_km'] != null
          ? (map['starting_km'] as num).toDouble()
          : null,
      startingImageUrl: map['starting_image_url'],
      endingKm: map['ending_km'] != null
          ? (map['ending_km'] as num).toDouble()
          : null,
      endingImageUrl: map['ending_image_url'],
      isCompleted: map['is_completed'] ?? false,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'driver_name': driverName,
      'consignee': consignee,
      'container_number': containerNumber,
      'vehicle_number': vehicleNumber,
      'destination': destination,
      'starting_km': startingKm,
      'starting_image_url': startingImageUrl,
      'ending_km': endingKm,
      'ending_image_url': endingImageUrl,
      'is_completed': isCompleted,
    };
  }
}

class TripManagementScreen extends StatefulWidget {
  final String? initialDriverName;
  final String? filterDriver;
  final bool readOnly;
  const TripManagementScreen({
    super.key,
    this.initialDriverName,
    this.filterDriver,
    this.readOnly = false,
  });

  @override
  State<TripManagementScreen> createState() => _TripManagementScreenState();
}

class _TripManagementScreenState extends State<TripManagementScreen> {
  final List<Trip> _trips = [];
  bool _isLoading = true;
  final _supabase = Supabase.instance.client;

  @override
  void initState() {
    super.initState();
    _loadData().then((_) {
      if (widget.initialDriverName != null && widget.filterDriver == null) {
        _showAddTripDialog(prefilledDriver: widget.initialDriverName);
      }
    });
  }

  Future<void> _loadData() async {
    setState(() => _isLoading = true);
    await userManager.fetchUsers();
    await _fetchTrips();
    setState(() => _isLoading = false);
  }

  Future<void> _fetchTrips() async {
    try {
      dynamic query = _supabase.from('trips').select();
      if (widget.filterDriver != null) {
        query = query.eq('driver_name', widget.filterDriver!);
      }
      final data = await query.order('created_at', ascending: false);
      setState(() {
        _trips.clear();
        _trips.addAll((data as List).map((row) => Trip.fromMap(row)).toList());
      });
    } catch (e) {
      debugPrint('Error fetching trips: $e');
    }
  }

  Future<void> _addTrip({
    required String driverName,
    required String consignee,
    required String containerNumber,
    required String vehicleNumber,
    String? destination,
    required double startingKm,
  }) async {
    try {
      final newTrip = Trip(
        id: '', // Will be generated by DB
        driverName: driverName,
        consignee: consignee,
        containerNumber: containerNumber,
        vehicleNumber: vehicleNumber,
        destination: destination,
        startingKm: startingKm,
      );

      final response = await _supabase
          .from('trips')
          .insert(newTrip.toMap())
          .select()
          .single();
      setState(() {
        _trips.insert(0, Trip.fromMap(response));
      });
    } catch (e) {
      debugPrint('Error adding trip: $e');
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error starting trip: $e')));
      }
    }
  }

  void _showAddTripDialog({String? prefilledDriver}) {
    final driverController = TextEditingController(text: prefilledDriver);
    final consigneeController = TextEditingController();
    final containerController = TextEditingController();
    final vehicleController = TextEditingController();
    final destinationController = TextEditingController();
    final kmController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text(
          'START NEW JOURNEY',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Autocomplete<String>(
                optionsBuilder: (TextEditingValue textEditingValue) {
                  final options = userManager.allowedUsers;
                  if (textEditingValue.text.isEmpty) {
                    return options;
                  }
                  return options.where(
                    (option) => option.toLowerCase().contains(
                      textEditingValue.text.toLowerCase(),
                    ),
                  );
                },
                onSelected: (String selection) {
                  driverController.text = selection;
                },
                fieldViewBuilder:
                    (context, controller, focusNode, onFieldSubmitted) {
                      // Pre-fill the visible text field if a driver was selected from the registry
                      if (prefilledDriver != null &&
                          controller.text.isEmpty &&
                          driverController.text == prefilledDriver) {
                        controller.text = prefilledDriver;
                      }

                      return TextField(
                        controller: controller,
                        focusNode: focusNode,
                        onChanged: (value) => driverController.text = value,
                        decoration: AppTheme.inputDecoration(
                          'Search Driver',
                          icon: Icons.person_search,
                        ),
                      );
                    },
                optionsViewBuilder: (context, onSelected, options) {
                  return Align(
                    alignment: Alignment.topLeft,
                    child: Material(
                      elevation: 8,
                      borderRadius: BorderRadius.circular(8),
                      child: Container(
                        width:
                            MediaQuery.of(context).size.width -
                            100, // Account for dialog padding
                        constraints: const BoxConstraints(maxHeight: 200),
                        child: ListView.builder(
                          padding: EdgeInsets.zero,
                          shrinkWrap: true,
                          itemCount: options.length,
                          itemBuilder: (context, index) {
                            final option = options.elementAt(index);
                            return ListTile(
                              title: Text(
                                option,
                                style: const TextStyle(
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              onTap: () => onSelected(option),
                              hoverColor: AppTheme.primaryBlue.withOpacity(
                                0.05,
                              ),
                            );
                          },
                        ),
                      ),
                    ),
                  );
                },
              ),
              const SizedBox(height: 16),
              TextField(
                controller: consigneeController,
                decoration: AppTheme.inputDecoration(
                  'Consignee',
                  icon: Icons.business,
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: containerController,
                decoration: AppTheme.inputDecoration(
                  'Container Number',
                  icon: Icons.inventory,
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: vehicleController,
                decoration: AppTheme.inputDecoration(
                  'Vehicle Number',
                  icon: Icons.local_shipping,
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: destinationController,
                decoration: AppTheme.inputDecoration(
                  'Destination (Optional)',
                  icon: Icons.map,
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: kmController,
                keyboardType: TextInputType.number,
                decoration: AppTheme.inputDecoration(
                  'Starting Odometer (KM)',
                  icon: Icons.speed,
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text(
              'CANCEL',
              style: TextStyle(
                color: AppTheme.accentWarning,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              final driver = driverController.text.trim();
              final consignee = consigneeController.text.trim();
              final container = containerController.text.trim();
              final vehicle = vehicleController.text.trim();
              final odometer = kmController.text.trim();

              String? error;
              if (driver.isEmpty) {
                error = 'Driver name is required';
              } else if (consignee.isEmpty) {
                error = 'Consignee is required';
              } else if (container.isEmpty) {
                error = 'Container number is required';
              } else if (vehicle.isEmpty) {
                error = 'Vehicle number is required';
              } else if (odometer.isEmpty) {
                error = 'Starting odometer is required';
              }

              if (error == null) {
                _addTrip(
                  driverName: driver,
                  consignee: consignee,
                  containerNumber: container,
                  vehicleNumber: vehicle,
                  destination: destinationController.text.isNotEmpty
                      ? destinationController.text
                      : null,
                  startingKm: double.parse(odometer),
                );
                Navigator.pop(context);
              } else {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(error),
                    backgroundColor: AppTheme.accentWarning,
                  ),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primaryBlue,
            ),
            child: const Text('START TRIP'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundLight,
      appBar: AppBar(
        title: Text(
          widget.filterDriver != null
              ? 'LOGS: ${widget.filterDriver!.toUpperCase()}'
              : 'JOURNEY LOGS',
        ),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                _buildSummaryHeader(),
                Expanded(
                  child: _trips.isEmpty ? _buildEmptyState() : _buildTripList(),
                ),
              ],
            ),
      floatingActionButton: widget.readOnly
          ? null
          : FloatingActionButton.extended(
              onPressed: _showAddTripDialog,
              backgroundColor: AppTheme.primaryBlue,
              icon: const Icon(Icons.add),
              label: const Text(
                'NEW JOURNEY',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
            ),
    );
  }

  Widget _buildSummaryHeader() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(
          bottom: BorderSide(color: Colors.grey.shade300, width: 1.5),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Operational Status',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.bold,
              color: AppTheme.textSecondary,
            ),
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              _buildSimpleStat(
                'ACTIVE',
                _trips.where((t) => !t.isCompleted).length.toString(),
                AppTheme.primaryBlue,
              ),
              const SizedBox(width: 40),
              _buildSimpleStat(
                'COMPLETED',
                _trips.where((t) => t.isCompleted).length.toString(),
                AppTheme.accentSuccess,
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSimpleStat(String label, String value, Color color) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          value,
          style: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: color,
          ),
        ),
        Text(
          label,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w900,
            color: AppTheme.textSecondary,
          ),
        ),
      ],
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.assignment_outlined,
            size: 100,
            color: Colors.grey.shade400,
          ),
          const SizedBox(height: 24),
          const Text(
            'No Active Journeys',
            style: TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.bold,
              color: AppTheme.textSecondary,
            ),
          ),
          const SizedBox(height: 12),
          const Text(
            'Tap the blue button below to start tracking a new trip.',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 16, color: AppTheme.textSecondary),
          ),
        ],
      ),
    );
  }

  Widget _buildTripList() {
    return ListView.builder(
      padding: const EdgeInsets.all(20),
      itemCount: _trips.length,
      itemBuilder: (context, index) {
        final trip = _trips[index];
        return _buildTripCard(trip);
      },
    );
  }

  Widget _buildTripCard(Trip trip) {
    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      decoration: AppTheme.cardDecoration(),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: () {
            if (widget.readOnly) {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => AdminTripDetailView(trip: trip),
                ),
              );
            } else {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => TripDetailScreen(trip: trip),
                ),
              ).then((_) => _fetchTrips());
            }
          },
          borderRadius: BorderRadius.circular(12),
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color:
                            (trip.isCompleted
                                    ? AppTheme.accentSuccess
                                    : AppTheme.primaryBlue)
                                .withOpacity(0.1),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: Icon(
                        trip.isCompleted
                            ? Icons.check_circle
                            : Icons.pending_actions,
                        color: trip.isCompleted
                            ? AppTheme.accentSuccess
                            : AppTheme.primaryBlue,
                        size: 32,
                      ),
                    ),
                    const SizedBox(width: 20),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'CONSIGNEE: ${trip.consignee.toUpperCase()}',
                            style: const TextStyle(
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                              color: AppTheme.textMain,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'DRIVER: ${trip.driverName}',
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.bold,
                              color: AppTheme.primaryBlue,
                            ),
                          ),
                          if (trip.destination != null &&
                              trip.destination!.isNotEmpty)
                            Text(
                              'DESTINATION: ${trip.destination}',
                              style: const TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                color: AppTheme.textSecondary,
                              ),
                            ),
                          Text(
                            'VEHICLE: ${trip.vehicleNumber} | CONT: ${trip.containerNumber}',
                            style: const TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.bold,
                              color: AppTheme.textSecondary,
                            ),
                          ),
                        ],
                      ),
                    ),
                    if (trip.isCompleted)
                      const Chip(
                        label: Text(
                          'COMPLETED',
                          style: TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        backgroundColor: AppTheme.accentSuccess,
                      )
                    else
                      const Chip(
                        label: Text(
                          'ACTIVE',
                          style: TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        backgroundColor: AppTheme.primaryBlue,
                      ),
                  ],
                ),
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 15),
                  child: Divider(),
                ),
                Row(
                  children: [
                    Expanded(
                      child: Wrap(
                        spacing: 16,
                        runSpacing: 8,
                        crossAxisAlignment: WrapCrossAlignment.center,
                        children: [
                          _buildCompactInfo(
                            Icons.play_circle_outline,
                            'START:',
                            trip.startingKm != null
                                ? '${trip.startingKm} KM'
                                : '---',
                          ),
                          if (trip.endingKm != null)
                            _buildCompactInfo(
                              Icons.flag_circle_outlined,
                              'END:',
                              '${trip.endingKm} KM',
                            ),
                          if (trip.startingImageUrl != null)
                            _buildThumbnail(trip.startingImageUrl!, 'START'),
                          if (trip.endingImageUrl != null)
                            _buildThumbnail(trip.endingImageUrl!, 'END'),
                        ],
                      ),
                    ),
                    const Icon(
                      Icons.arrow_forward_ios,
                      size: 16,
                      color: Colors.grey,
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildThumbnail(String url, String label) {
    return InkWell(
      onTap: () => _showFullImage(url),
      child: Column(
        children: [
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(6),
              border: Border.all(color: AppTheme.primaryBlue.withOpacity(0.3)),
              image: DecorationImage(image: NetworkImage(url), fit: BoxFit.cover),
            ),
          ),
          Text(
            label,
            style: const TextStyle(
              fontSize: 8,
              fontWeight: FontWeight.bold,
              color: AppTheme.textSecondary,
            ),
          ),
        ],
      ),
    );
  }

  void _showFullImage(String url) {
    showDialog(
      context: context,
      builder: (context) => Dialog(
        backgroundColor: Colors.transparent,
        insetPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 40),
        child: Stack(
          alignment: Alignment.topRight,
          children: [
            Container(
              width: double.infinity,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12),
                color: Colors.white,
                image: DecorationImage(image: NetworkImage(url), fit: BoxFit.contain),
              ),
            ),
            Positioned(
              top: 10,
              right: 10,
              child: GestureDetector(
                onTap: () => Navigator.pop(context),
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: const BoxDecoration(
                    color: Colors.black54,
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(Icons.close, color: Colors.white, size: 24),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCompactInfo(IconData icon, String label, String value) {
    return Row(
      children: [
        Icon(icon, size: 16, color: Colors.grey),
        const SizedBox(width: 8),
        Text(
          label,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.bold,
            color: AppTheme.textSecondary,
          ),
        ),
        const SizedBox(width: 5),
        Text(
          value,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            color: AppTheme.textMain,
          ),
        ),
      ],
    );
  }
}
